server:
  port: 8090
  servlet:
    context-path: /demo

spring:
  data:
    redis:
      host: redis
      # ??????????????Duration?
      timeout: 10000ms
      # Redis??????16???????????????
      # database: 0
      lettuce:
        pool:
          # ???????????????????? ?? 8
          max-active: 8
          # ??????????????????????? ?? -1
          max-wait: -1ms
          # ??????????? ?? 8
          max-idle: 8
          # ??????????? ?? 0
          min-idle: 0
      port: 6379
  cache:
    # ???????????Spring Cache ???????????
    type: redis
