name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_USERNAME: ec2-user
          AWS_INSTANCE_IP: <YOUR_EC2_INSTANCE_IP>
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}

      - name: Upload jar to EC2
        run: |
          scp -i ${{ secrets.AWS_PRIVATE_KEY }} path/to/your-jar.jar $SSH_USERNAME@$AWS_INSTANCE_IP:/path/to/destination

      - name: Start jar on EC2
        run: |
          ssh -i ${{ secrets.AWS_PRIVATE_KEY }} $SSH_USERNAME@$AWS_INSTANCE_IP "java -jar /path/to/your-jar.jar &"