name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_USERNAME: ec2-user
          AWS_INSTANCE_IP: 52.80.40.170
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}
      - name: Package jar
        run: mvn clean package

      - name: Upload jar to EC2
        run: |
          scp -i ${{ secrets.AWS_PRIVATE_KEY }} .target/demo1-0.0.1-SNAPSHOT.jar $SSH_USERNAME@$AWS_INSTANCE_IP:/vdb/soft/api/test

      - name: Start jar on EC2
        run: |
          ssh -i ${{ secrets.AWS_PRIVATE_KEY }} $SSH_USERNAME@$AWS_INSTANCE_IP "java -jar .target/demo1-0.0.1-SNAPSHOT.jar &"
