name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: User PEM key
        run: echo "${{ secrets.AWS_PRIVATE_KEY }}" | base64 -d > raymond.pem

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ec2-user
          AWS_INSTANCE_IP: ec2-52-80-40-170.cn-north-1.compute.amazonaws.com.cn
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean package



      - name: Upload jar to EC2
        run: |
          scp -i raymond.pem -o StrictHostKeyChecking=no /home/runner/work/demo1/demo1/target/demo1-0.0.1-SNAPSHOT.jar /home/runner/work/demo1/demo1/.github/workflows/run.sh ec2-user@ec2-52-80-40-170.cn-north-1.compute.amazonaws.com.cn:/vdb/soft/api

      - name: Start jar on EC2
        run: |
          ssh -i raymond.pem -o StrictHostKeyChecking=no ec2-user@ec2-52-80-40-170.cn-north-1.compute.amazonaws.com.cn "cd /vdb/soft/api && chmod +x run.sh && ./run.sh"
