name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: MIIEpAIBAAKCAQEA3rmGL5keAEkeV4p7CToFIL+DRw7f2+NrnF0Ul5+yX4nvzSZ7x8T2v6hnPsXydyjbdCuwUTDgBIaFncU7vSgmViTiU7+GrwRShzmzhYUpSnnv40lx
0QvgjpVGikunX3extBs85vgJR3HsNphZocqVU9a1P1n1OxEUP69C1jqbIXF2xiGA
hTuYsxEKwO5zzdo8OAe/JtcJxDxZhW4qwxyUG0IIiZT/tE4trvQnyC2cip5elRzz
VeWEOIItVAn2rLVwWRk7NjKRLm9Qaqm8Gh7eq6HiY7HCq3lvW2CCabudW7Myi+aN
h9wcjoC4hKue8CqP2HENVnK5yCZmVNdYX6gXjwIDAQABAoIBAGFSVgUkdgyP5rc/
5qVQef8mUBnTsRPnWxVXQvFCMfI3Vtag80OGmH+E+aBfZKSW8NXhZUkE/05a7bXU
AleUXLQVp+QKc7K0Q8+c8gns9u75O05owFglRXloVwuFJVy886SMpl8SkRNr/1iX
18qvt/KLhmVpTJQD0YJGdgEgWLsShaNtdjZei/fWKzv9IlbDTiFSxSkbmyGWD88h
BWwnpy4ztVv31IkOGxjFEWsX+lW0k4vIJskH/POlr7l2ohsygYB+DLGLzANkMld6
q4bvkXXgOWs23R5oy6m35qaXJq2LcETR9LVVWFITIIzzeTGRPfikF2LYLOQY9AHq
3OxLu6kCgYEA9JEfvrFzcCx7w9T1ZrXo47+u9kLZCKcHyorH9uv+wLVjBFcm5cF/
3UdK+A8lCzfPm0HNYQFMN5hluDbkPqUpN8xiXsvL/h9HNtt6Lkm1+FhBM+DZIyAH
g33eK5yIcRxgE/sPe+Y0c2ARzqkJVU3u/XpgVwMRtikygqVNAHk6f6UCgYEA6SMA
eRsoKAogW11t8yk3jqfX2uwxGa2VzsBtigPt8WHbuwe7wRBvQBCNlqseviGItgCd
RwgUMMg+ZbpISqyeaBAjPdwP1GMkJqZNm8NiU12UlzOz0P7YdyxwkrET+wd/HwdA
IUFOAD1APCCXyE5LxjMaAAX8HdaFnGmQMzzk1CMCgYEAnQNK6SeN4Fd+wfRH9MAX
G5iloE68ffSWaO9+f8V1UY1iW5gETf9TsuGhfO5kLvaO37N4Qq4Nm6fIrmL3WEy6
0Kr0AL5AYg78rnhr0anbHOy0N7VEUmuuxzmY2FDvvAamnE1T3Iyn4easqAwYBN86
7xuRHGvJBDUgy4WKkSJDb00CgYBDU3ZZgvwvw+zgNbUA2dBPhC0T7c2oKrbuhCee
CdB3Otlnw6327TYTfDRHZJd2NNz0Im1JDA44oDtUyV0DI6KDTtW+kYSIwzC3cKNM
7jnA9W9p0uaE3nPIxq6jzjuE7P9LCJ7+e4t5Cjc4pfjvQZ0kWbGSfCf4vfDL4Lhh
853pnQKBgQCMTGWG1r9b2ZsIhgAqSOem2ibDxxxf5NXueqTi6eEdQMHAtb0xH1iy
7JGm2u+HMZWSNk5MxROlqa7WO1ETlW9NSd5Lwtewa0yrRZKPc4y74gu1zwNe3TjX
DjFr3KKYqdSr7x9/GgUlojvrNhA2WRiFAFs+RWPjFetLy0rVdhcnng==
          SSH_USERNAME: ec2-user
          AWS_INSTANCE_IP: ec2-52-80-40-170.cn-north-1.compute.amazonaws.com.cn
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: MIIEpAIBAAKCAQEA3rmGL5keAEkeV4p7CToFIL+DRw7f2+NrnF0Ul5+yX4nvzSZ7x8T2v6hnPsXydyjbdCuwUTDgBIaFncU7vSgmViTiU7+GrwRShzmzhYUpSnnv40lx
0QvgjpVGikunX3extBs85vgJR3HsNphZocqVU9a1P1n1OxEUP69C1jqbIXF2xiGA
hTuYsxEKwO5zzdo8OAe/JtcJxDxZhW4qwxyUG0IIiZT/tE4trvQnyC2cip5elRzz
VeWEOIItVAn2rLVwWRk7NjKRLm9Qaqm8Gh7eq6HiY7HCq3lvW2CCabudW7Myi+aN
h9wcjoC4hKue8CqP2HENVnK5yCZmVNdYX6gXjwIDAQABAoIBAGFSVgUkdgyP5rc/
5qVQef8mUBnTsRPnWxVXQvFCMfI3Vtag80OGmH+E+aBfZKSW8NXhZUkE/05a7bXU
AleUXLQVp+QKc7K0Q8+c8gns9u75O05owFglRXloVwuFJVy886SMpl8SkRNr/1iX
18qvt/KLhmVpTJQD0YJGdgEgWLsShaNtdjZei/fWKzv9IlbDTiFSxSkbmyGWD88h
BWwnpy4ztVv31IkOGxjFEWsX+lW0k4vIJskH/POlr7l2ohsygYB+DLGLzANkMld6
q4bvkXXgOWs23R5oy6m35qaXJq2LcETR9LVVWFITIIzzeTGRPfikF2LYLOQY9AHq
3OxLu6kCgYEA9JEfvrFzcCx7w9T1ZrXo47+u9kLZCKcHyorH9uv+wLVjBFcm5cF/
3UdK+A8lCzfPm0HNYQFMN5hluDbkPqUpN8xiXsvL/h9HNtt6Lkm1+FhBM+DZIyAH
g33eK5yIcRxgE/sPe+Y0c2ARzqkJVU3u/XpgVwMRtikygqVNAHk6f6UCgYEA6SMA
eRsoKAogW11t8yk3jqfX2uwxGa2VzsBtigPt8WHbuwe7wRBvQBCNlqseviGItgCd
RwgUMMg+ZbpISqyeaBAjPdwP1GMkJqZNm8NiU12UlzOz0P7YdyxwkrET+wd/HwdA
IUFOAD1APCCXyE5LxjMaAAX8HdaFnGmQMzzk1CMCgYEAnQNK6SeN4Fd+wfRH9MAX
G5iloE68ffSWaO9+f8V1UY1iW5gETf9TsuGhfO5kLvaO37N4Qq4Nm6fIrmL3WEy6
0Kr0AL5AYg78rnhr0anbHOy0N7VEUmuuxzmY2FDvvAamnE1T3Iyn4easqAwYBN86
7xuRHGvJBDUgy4WKkSJDb00CgYBDU3ZZgvwvw+zgNbUA2dBPhC0T7c2oKrbuhCee
CdB3Otlnw6327TYTfDRHZJd2NNz0Im1JDA44oDtUyV0DI6KDTtW+kYSIwzC3cKNM
7jnA9W9p0uaE3nPIxq6jzjuE7P9LCJ7+e4t5Cjc4pfjvQZ0kWbGSfCf4vfDL4Lhh
853pnQKBgQCMTGWG1r9b2ZsIhgAqSOem2ibDxxxf5NXueqTi6eEdQMHAtb0xH1iy
7JGm2u+HMZWSNk5MxROlqa7WO1ETlW9NSd5Lwtewa0yrRZKPc4y74gu1zwNe3TjX
DjFr3KKYqdSr7x9/GgUlojvrNhA2WRiFAFs+RWPjFetLy0rVdhcnng==
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Upload jar to EC2
        run: |
          scp -i $SSH_PRIVATE_KEY /home/runner/work/demo1/demo1/target/demo1-0.0.1-SNAPSHOT.jar $SSH_USERNAME@$AWS_INSTANCE_IP:/vdb/soft/api

      - name: Start jar on EC2
        run: |
          ssh -i $SSH_PRIVATE_KEY $SSH_USERNAME@$AWS_INSTANCE_IP "nohup java -jar /vdb/soft/api/demo1-0.0.1-SNAPSHOT.jar &"
